using System;
using System.Drawing;
using Word.Api.Interfaces;
using Word.Utils;
using Word.W2004;
using Word.W2004.Elements;
using Word.W2004.Elements.TableElements;
using Word.W2004.Style;
using Font = Word.W2004.Style.Font;
using Image = Word.W2004.Elements.Image;

namespace ConsoleTest
{
    class Program
    {
        static void Main()
        {
            IDocument myDoc = new Document2004();
            // myDoc.setPageOrientationLandscape();// default is Portrait be can be
            // changed.

            myDoc.AddEle(BreakLine.Times(1).Create()); // this is one breakline

            // Headings
            myDoc.AddEle(Heading2.With("===== Headings ======").Create());
            myDoc.AddEle(Paragraph
                    .With("This doc has been generated by the unit test testJava2wordAllInOne() in the class DocumentTest2004Test.java.")
                    .Create());
            myDoc.AddEle(BreakLine.Times(1).Create());

            myDoc.AddEle(Paragraph
                    .With("I will try to use a little bit of everything in the API Java2word. "
                            + "I realised that is very dificult to keep the doucmentation updated "
                            + "so this is where I will demostrate how to do some cool things With Java2word!")
                    .Create());

            myDoc.AddEle(Heading1.With("Heading01 without styling").Create());
            myDoc.AddEle(Heading2.With("Heading02 With styling").WithStyle()
                    .Align(Align.CENTER).Italic().Create());
            myDoc.AddEle(Heading3.With("Heading03").WithStyle().Bold()
                    .Align(Align.RIGHT).Create());

            // Paragraph and ParagrapPiece
            myDoc.AddEle(Heading2.With("===== Paragraph and ParagrapPiece ======")
                    .Create());
            myDoc.AddEle(Paragraph.With("I am a very simple paragraph.").Create());

            myDoc.AddEle(BreakLine.Times(1).Create());
            ParagraphPiece myParPiece01 = ParagraphPiece
                    .With("If you use the class 'Paragraph', you will have limited style. Maybe only paragraph aligment.");
            ParagraphPiece myParPiece02 = ParagraphPiece
                    .With("In order to use more advanced style, you have to use ParagraphPiece");
            ParagraphPiece myParPiece03 = ParagraphPiece
                    .With("One example of this is when you want to make ONLY one word BOLD or ITALIC. the way to to this is Create many pieces, format them separetely and put all together in a Paragraph object. Example:");

            myDoc.AddEle(Paragraph.WithPieces(myParPiece01, myParPiece02,
                    myParPiece03).Create());

            ParagraphPiece myParPieceJava = ParagraphPiece.With("I like Java and ")
                    .WithStyle().Font(Font.COURIER).Create();
            ParagraphPiece myParPieceRuby = ParagraphPiece.With("Ruby!!! ")
                    .WithStyle().Bold().Italic().Create();
            ParagraphPiece myParPieceAgile = ParagraphPiece
                    .With("I actually love Java, Ruby Agile, BDD, Cucumber, automation... ")
                    .WithStyle().TextColor("008000").Create();

            myDoc.AddEle(Paragraph.WithPieces(myParPieceJava, myParPieceRuby,
                    myParPieceAgile).Create());

            myDoc.AddEle(BreakLine.Times(2).Create());
            myDoc.AddEle(Paragraph.WithPieces(
                    ParagraphPiece.With("This is a manual 'Bold' and 'Italic'")
                            .WithStyle().Font(Font.COURIER).Bold().Italic()
                            .Create()).Create());
            myDoc.AddEle(Paragraph
                    .WithPieces(
                            ParagraphPiece
                                    .With("This is the SAME as the above line but With 'Smart' Bold/Align ")
                                    .WithStyle().Font(Font.COURIER_BOLD_ITALIC)
                                    .Create()).Create());
            myDoc.AddEle(BreakLine.Times(1).Create());

            // Font size
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("No size")
                    .Create(), ParagraphPiece.With("I am size 24.").WithStyle()
                    .FontSize(24).Create()));

            //ParagraphPiece and other format/styles
            myDoc.AddEle(BreakLine.Times(1).Create());
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("New ParagraphPiece styles have been implemented. Here they are:").WithStyle().FontSize(14).Create()));

            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("Subscript").WithStyle().Subscript().Create()));
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("Superscript").WithStyle().Superscript().Create()));
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("Strike").WithStyle().Strike().Create()));
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("Caps").WithStyle().Caps().Create()));
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("SmallCaps").WithStyle().SmallCaps().Create()));
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("DoubleStrike").WithStyle().DoubleStrike().Create()));
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("Emboss").WithStyle().Emboss().Create()));
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("Imprint").WithStyle().Imprint().Create()));
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("Outline").WithStyle().Outline().Create()));
            myDoc.AddEle(Paragraph.WithPieces(ParagraphPiece.With("The Style is: ").Create(), ParagraphPiece.With("Shadow").WithStyle().Shadow().Create()));
            myDoc.AddEle(BreakLine.Times(2).Create());


            // Document Header and Footer
            myDoc.AddEle(BreakLine.Times(2).Create());
            myDoc.AddEle(Heading2.With("===== Document Header and Footer ======")
                    .Create());
            myDoc.AddEle(Paragraph
                    .With("By default everything is added to the Body when you do 'myDoc.AddEle(...)'."
                            + " But you can add elements to the Header and/or Footer. Other cool thing is show page number or not.")
                    .Create());

            myDoc.AddEle(BreakLine.Times(2).Create());
            myDoc.AddEle(Paragraph
                    .With("Page number is displayed by default but you can disable: 'myDoc.Footer().showPageNumber(false)' ")
                    .Create());

            myDoc.AddEle(BreakLine.Times(2).Create());
            myDoc.AddEle(Paragraph
                    .With("you can also hide Header and Footer in the first Page. This is useful for when you have a cover page.: 'myDoc.Header.setHideHeaderAndFooterFirstPage(true)' ")
                    .Create());

            myDoc.Header.AddEle(
                    Paragraph.WithPieces(
                            ParagraphPiece.With("I am in the"),
                            ParagraphPiece.With(" Header ").WithStyle().Bold()
                                    .Create(), ParagraphPiece.With("of all pages"))
                            .Create());

            myDoc.Footer.AddEle(
                    Paragraph.With("I am in the Footer of all pages").Create());

            // Images
            myDoc.AddEle(BreakLine.Times(1).Create());
            myDoc.AddEle(Heading2.With("===== Images ======").Create());
            myDoc.AddEle(Paragraph
                    .With("Images can be created from diferent locations. It can be from your local machine, from web URL or classpath.")
                    .Create());

            myDoc.AddEle(Paragraph.With(
                    "This one is coming from WEB, google web site: ").Create());
            myDoc.AddEle(Image
                    .From_WEB_URL("http://www.google.com/images/logos/ps_logo2.png"));

            myDoc.AddEle(BreakLine.Times(2).Create());
            myDoc.AddEle(Paragraph.With("You can change the image dimensions:.")
                    .Create());
            myDoc.AddEle(Image
                    .From_WEB_URL("http://www.google.com/images/logos/ps_logo2.png")
                    .SetHeight(40).SetWidth(80).Create());

            myDoc.AddEle(BreakLine.Times(2).Create());
            myDoc.AddEle(Paragraph
                    .With("You can always be creative mixing up images inside other IElements. Eg.: Paragraphs, Tables, etc.")
                    .Create());

            /*myDoc.AddEle(Paragraph
                    .With("This document inside the paragraph, coming from '/src/test/resources/dtpick.gif': "
                            + Image.From_FULL_LOCAL_PATHL(
                                    Util.AppRoot
                                            + "/src/test/resources/dtpick.gif")
                                    .Content));*/

            myDoc.AddEle(BreakLine.Times(1).Create());

            // Table
            myDoc.AddEle(Heading2.With("===== Table ======").Create());
            myDoc.AddEle(Paragraph
                    .With("Table os soccer playerd and their number of gols - the best of the best of all Times:")
                    .Create());
            myDoc.AddEle(BreakLine.Times(1).Create());

            Table tbl = new Table();
            tbl.AddTableEle(TableEle.TH, "Name", "Number of gols", "Country");
            tbl.SetRepeatTableHeaderOnEveryPage();

            tbl.AddTableEle(TableEle.TD, "Arthur Friedenreich", "1329", "Brazil");
            tbl.AddTableEle(TableEle.TD, "Pele", "1281", "Brazil");
            tbl.AddTableEle(TableEle.TD, "Romario", "1002", "Brazil");
            tbl.AddTableEle(TableEle.TD, "Tulio Maravilha", "956", "Brazil");
            tbl.AddTableEle(TableEle.TD, "Zico", "815", "Brazil");
            tbl.AddTableEle(TableEle.TD, "Roberto Dinamite", "748", "Brazil");
            tbl.AddTableEle(TableEle.TD, "Di Stéfano", "715", "Argentina");
            tbl.AddTableEle(TableEle.TD, "Puskas", "689", "Hungary");
            tbl.AddTableEle(TableEle.TD, "Flávio", "591", "Brazil");
            tbl.AddTableEle(TableEle.TD, "James McGory", "550", "Scotland");
            tbl.AddTableEle(TableEle.TD, "Leonardo Correa", "299",
                    "Brazil/Australia");

            tbl.AddTableEle(TableEle.TF, "Total", "1,100,000.00", " ");

            myDoc.AddEle(tbl);

            myDoc.AddEle(BreakLine.Times(1).Create());

            myDoc.AddEle(Paragraph
                    .WithPieces(
                            ParagraphPiece
                                    .With("* Zico was mid-fieldfer and managed to score all those fucking goals!")
                                    .WithStyle().Italic().Create()).Create());
            myDoc.AddEle(Paragraph
                    .WithPieces(
                            ParagraphPiece
                                    .With("* Leonardo Correa's goals (me) include futsal, soccer, friendly games, training games, so on... (but not playstation)")
                                    .WithStyle().Italic().Create()).Create());

            // PageBreaks
            myDoc.AddEle(Heading2.With("===== PageBreak ======").Create());
            myDoc.AddEle(Paragraph.With("There is a PAGE BREAK after this line:")
                    .Create());
            myDoc.AddEle(PageBreak.Create());
            myDoc.AddEle(Paragraph.With("There is a PAGE BREAK before this line:")
                    .Create());

            myDoc.Save(@"c:\mytest.doc");
        }

    }
}